agent_policy:
  clip_param: 0.3
  entropy_coeff: 0.025
  entropy_coeff_schedule: null
  gamma: 0.998
  grad_clip: 10.0
  kl_coeff: 0.0
  kl_target: 0.01
  lambda: 0.98
  lr: 0.0003
  lr_schedule: null
  model:
    custom_model: keras_conv_lstm
    custom_options:
      fc_dim: 128
      idx_emb_dim: 4
      input_emb_vocab: 100
      lstm_cell_size: 128
      num_conv: 2
      num_fc: 2
    max_seq_len: 25
  use_gae: true
  vf_clip_param: 50.0
  vf_loss_coeff: 0.05
  vf_share_layers: false
env:
  agent_morality:
  - 100.0
  - 0.0
  - 0.0
  - 0.0
  components:
  - Build:
      build_labor: 10
      payment: 10
      payment_max_skill_multiplier: 3
      skill_dist: predefined
  - ContinuousDoubleAuction:
      max_bid_ask: 10
      max_num_orders: 5
      order_duration: 50
      order_labor: 0.25
  - Gather:
      collect_labor: 1
      move_labor: 1
      skill_dist: pareto
  - Steal:
      skill_dist: pareto
      steal_labor: 1
  dense_log_frequency: 20
  energy_cost: 0.21
  energy_warmup_constant: 10000
  energy_warmup_method: auto
  env_layout_file: quadrant_25x25_20each_30clump.txt
  episode_length: 1000
  fixed_four_skill_and_loc: true
  flatten_masks: true
  flatten_observations: true
  isoelastic_eta: 0.23
  moral_theory: virtue_ethics
  multi_action_mode_agents: false
  multi_action_mode_planner: true
  n_agents: 4
  planner_gets_spatial_info: false
  planner_reward_type: coin_eq_times_productivity
  scenario_name: moral_layout_from_file/simple_wood_and_stone
  starting_agent_coin: 0
  world_size:
  - 25
  - 25
general:
  ckpt_frequency_steps: 750000
  cpus: 4
  episodes: 1
  gpus: 1
  restore_tf_weights_agents: ./ai_economist/training/rllib/envs/virtue_ethics/layout/agent_morality=[100.0,0.0,0.0,0.0]/ckpts/agent.tf.weights.global-step-2508000
  restore_tf_weights_planner: ''
  train_planner: false
planner_policy:
  clip_param: 0.3
  entropy_coeff: 0.025
  entropy_coeff_schedule: null
  gamma: 0.998
  grad_clip: 10.0
  kl_coeff: 0.0
  kl_target: 0.01
  lambda: 0.98
  lr: 0.0003
  lr_schedule: null
  model:
    custom_model: random
    custom_options: {}
    max_seq_len: 25
  use_gae: true
  vf_clip_param: 50.0
  vf_loss_coeff: 0.05
  vf_share_layers: false
trainer:
  batch_mode: truncate_episodes
  env_config: null
  local_tf_session_args:
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 24
  metrics_smoothing_episodes: null
  multiagent: null
  no_done_at_end: false
  num_envs_per_worker: 2
  num_gpus: 1
  num_gpus_per_worker: 0.5
  num_sgd_iter: 1
  num_workers: 4
  observation_filter: NoFilter
  rollout_fragment_length: 200
  seed: null
  sgd_minibatch_size: 1500
  shuffle_sequences: true
  tf_session_args:
    allow_soft_placement: true
    device_count:
      CPU: 4
      GPU: 1
    gpu_options:
      allow_growth: true
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 24
    log_device_placement: false
  train_batch_size: 6000
